services:
  # Serviço do Banco de Dados MySQL
  database:
    image: mysql:8.0
    container_name: vozes_db_container
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vozespass
      - MYSQL_DATABASE=vozes
      - MYSQL_USER=vozesuser
      - MYSQL_PASSWORD=vozespass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "--protocol=tcp",
          "-h",
          "127.0.0.1",
          "-u",
          "vozesuser",
          "-pvozespass",
          "-e",
          "SELECT 1;",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Serviço do Back-end Spring Boot
  backend:
    container_name: vozes_api_container
    build:
      context: ./backend/vozes-api
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/vozes
      - SPRING_DATASOURCE_USERNAME=vozesuser
      - SPRING_DATASOURCE_PASSWORD=vozespass
      - API_SECURITY_TOKEN_SECRET=sua-chave-secreta-aqui

  # Serviço do Front-end React
  frontend:
    container_name: vozes_frontend_container
    build:
      context: ./frontend/vozes-react
    ports:
      - "5173:80"

volumes:
  mysql_data:
