version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  database:
    image: postgres:15-alpine # Usa uma imagem oficial e leve do Postgres
    container_name: vozes_db_container
    ports:
      - "5432:5432" # Mapeia a porta do contêiner para a sua máquina
    environment:
      - POSTGRES_USER=vozesuser
      - POSTGRES_PASSWORD=vozespass
      - POSTGRES_DB=vozes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Serviço do Back-end Spring Boot
  backend:
    container_name: vozes_api_container
    build:
      context: ./backend/vozes-api # Caminho para o Dockerfile do backend
    ports:
      - "8080:8080" # Mapeia a porta da API
    depends_on:
      - database # Diz ao Docker para iniciar o banco ANTES do backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/vozes
      - SPRING_DATASOURCE_USERNAME=vozesuser
      - SPRING_DATASOURCE_PASSWORD=vozespass
      - API_SECURITY_TOKEN_SECRET=sua-chave-secreta-aqui

  # Serviço do Front-end React
  frontend:
    container_name: vozes_frontend_container
    build:
      # MUDANÇA: O contexto agora aponta para a pasta correta do seu projeto React.
      context: ./frontend/vozes-react
    ports:
      - "5173:80" # Mapeia a porta 80 do Nginx para a porta 5173 da sua máquina

volumes:
  postgres_data:
